"""Collect the headline numbers of every region from the saved result files into results/summary.md.

Nothing is recomputed: the tables are parsed from results/<region>/experiment.txt and boosting.txt, so the
summary can be regenerated and compared with the source files.

    python scripts/summarize_regions.py
"""
import re
from pathlib import Path

RESULTS = Path(__file__).resolve().parents[1] / "results"
NL = chr(10)
REGIONS = [("poltavska", "Poltavska"), ("kyivska", "Kyivska"), ("kharkivska", "Kharkivska"), ("lvivska", "Lvivska")]
MODEL = "logreg[own+nbr+cty]"
BOOST = "hgb[own+nbr+cty]"

ROW = re.compile(r"^\s*(?P<fam>\S+)(?: \*post-hoc)?\s+(?P<chosen>\S*\|\S+)\s+(?P<val>[\d.]+)\s+(?P<brier>[\d.]+) "
                 r"\[(?P<blo>[\d.]+), (?P<bhi>[\d.]+)\]\s+(?P<pr>[\d.]+) \[(?P<plo>[\d.]+), (?P<phi>[\d.]+)\]")
DIFF = re.compile(r"^\s*(?P<model>\S+)\s+(?P<metric>pr_auc|brier)\s+(?P<d>-?[\d.]+) \[(?P<lo>-?[\d.]+), (?P<hi>-?[\d.]+)\]")


def sections(text: str) -> dict:
    """{horizon: lines} by the '===== H = n h' headers."""
    out, cur = {}, None
    for line in text.splitlines():
        m = re.match(r"=+ H = (\d+) h", line)
        if m:
            cur = int(m.group(1))
            out[cur] = [line]  # keep the header: boosting prints its reference bar there
        elif cur is not None:
            out[cur].append(line)
    return out


def diffs(lines, ref: str, model: str) -> dict:
    """Paired differences of `model` to `ref` from the block 'Paired difference to <ref>'."""
    res, inside = {}, False
    for line in lines:
        if line.startswith("Paired difference to"):
            inside = line.split()[3].rstrip(";") == ref
            continue
        if inside:
            m = DIFF.match(line)
            if m and m["model"] == model:
                res[m["metric"]] = (float(m["d"]), float(m["lo"]), float(m["hi"]))
            elif not line.strip() and res:
                inside = False
    return res


def fmt_diff(d, digits) -> str:
    if d is None:
        return "n/a"
    v, lo, hi = d
    mark = " †" if (lo > 0 or hi < 0) else ""
    return f"{v:+.{digits}f} [{lo:+.{digits}f}, {hi:+.{digits}f}]{mark}"


def table(title: str, mode: str) -> list:
    """mode 'bar': reference chosen on validation (bar B); mode 'oracle': best baseline on the test block."""
    out = [f"## {title}", "",
           "| Region | H | positive in test / validation | reference | its Brier | its PR-AUC | logistic: dPR-AUC | logistic: dBrier | boosting: dPR-AUC | boosting: dBrier |",
           "|---|---|---|---|---|---|---|---|---|---|"]
    for slug, name in REGIONS:
        exp = sections((RESULTS / slug / "experiment.txt").read_text(encoding="utf-8"))
        bst = sections((RESULTS / slug / "boosting.txt").read_text(encoding="utf-8"))
        for h in (1, 3, 6):
            lines = exp[h]
            text = NL.join(lines)
            pos = re.search(r"positive rate ([\d.]+)%; validation rows \d+, positive rate ([\d.]+)%", text)
            if mode == "bar":
                ref = re.search(r"bar B \(incl\. post-hoc baselines\) = (\S+)", text)[1]
            else:
                ref = re.search(r"\(oracle, strict\) = (\S+)", text)[1]
            b = {m["fam"]: m for m in map(ROW.match, lines) if m}[ref]
            lg = diffs(lines, ref, MODEL)
            hg = {}
            if h in bst:
                ref_b = re.search(r"bar B = (\S+),", bst[h][0])[1] if mode == "bar" else re.search(r"best baseline on test = (\S+) =", bst[h][0])[1]
                hg = diffs(bst[h], ref_b, BOOST)
            out.append(f"| {name} | {h} | {pos[1]}% / {pos[2]}% | {ref} | {float(b['brier']):.4f} | {float(b['pr']):.3f} | "
                       f"{fmt_diff(lg.get('pr_auc'), 3)} | {fmt_diff(lg.get('brier'), 4)} | "
                       f"{fmt_diff(hg.get('pr_auc'), 3) if h in bst else 'n/a'} | {fmt_diff(hg.get('brier'), 4) if h in bst else 'n/a'} |")
    return out + [""]


def main() -> None:
    out = ["# Summary across oblasts (generated by scripts/summarize_regions.py, do not edit by hand)", "",
           "Test = last 8 weeks. Differences are paired (same resampled days); † marks an interval that excludes zero. "
           "PR-AUC: positive = better; Brier: negative = better. Models: logistic regression and boosting with all features.", ""]
    out += table("Against the baseline chosen on the validation block", "bar")
    out += table("Against the best baseline on the TEST block (strict: chosen with hindsight, favours the baselines)", "oracle")
    (RESULTS / "summary.md").write_text(NL.join(out) + NL, encoding="utf-8", newline=NL)  # LF on every system
    print(NL.join(out))


if __name__ == "__main__":
    main()
